language: node_js
node_js: "8"

sudo: required
services: mongodb

install: yarn

jobs:
  include:
    - stage: features_off
      before_script: yarn start & sleep 5
      script: yarn test
    - stage: features_on
      before_script: yarn start & sleep 5
      script: yarn testdev
